### ISSUE TITLE
Runworker results in 'assert "!" in channel'

### ISSUE THREAD

**Issue by MaxwellDPS** [CJWorkbench/channels_rabbitmq#42]
Hello I am trying to call ./mange.py runworker channel and getting an assertion error, Where should I start looking to fix this?

Thanks

ERROR:

```
root@radio:/app/trunkplayer# ./manage.py runworker channel
Running worker for channels ['c']
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/channels/management/commands/runworker.py", line 46, in handle
    worker.run()
  File "/usr/local/lib/python3.6/site-packages/asgiref/server.py", line 62, in run
    event_loop.run_until_complete(self.handle())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 30, in handle
    [listener.result() for listener in listeners]
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 30, in <listcomp>
    [listener.result() for listener in listeners]
  File "/usr/local/lib/python3.6/site-packages/channels/worker.py", line 37, in listener
    message = await self.channel_layer.receive(channel)
  File "/usr/local/lib/python3.6/site-packages/channels_rabbitmq/core.py", line 176, in receive
    assert "!" in channel
AssertionError
```

**Comment by adamhooper** [comment]
Workers -- "Normal channels" in Channels lingo -- are not supported by `channels_rabbitmq`. See [Deviations from the Channel Layer Specification](https://github.com/CJWorkbench/channels_rabbitmq#deviations-from-the-channel-layer-specification) in the README for alternative ideas that I think everybody should prefer.

If you really, really want "Normal channels", I would accept a fully-tested pull request. I have no fundamental reason not to support normal channels ... other than my personal opinion that most alternatives make more sense for most people.
