### ISSUE TITLE
RabbitMQ closed the connection: 403 ACCESS_REFUSED

### ISSUE THREAD

**Issue by COOLIRON2311** [CJWorkbench/channels_rabbitmq#46]
I am constantly getting RabbitMQ authentication error: 
```
$ daphne optimuspy.asgi:application
2023-05-29 14:01:48,798 INFO     Starting server at tcp:port=8000:interface=127.0.0.1
2023-05-29 14:01:48,799 INFO     HTTP/2 support not enabled (install the http2 and tls Twisted extras)
2023-05-29 14:01:48,799 INFO     Configuring endpoint tcp:port=8000:interface=127.0.0.1
2023-05-29 14:01:48,799 INFO     Listening on TCP address 127.0.0.1:8000
127.0.0.1:41030 - - [29/May/2023:14:01:53] "GET /tasks/e84e61173fb67aeb9726874f275d6795/result" 200 1833
127.0.0.1:41032 - - [29/May/2023:14:01:54] "WSCONNECTING /ws/ready/" - -
2023-05-29 14:01:54,063 ERROR    Failure connecting to RabbitMQ: RabbitMQ closed the connection: 403 ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.. Retrying
Traceback (most recent call last):
  File "C:\Users\ivani\source\repos\optimuspy\.venv\lib\site-packages\channels_rabbitmq\core.py", line 256, in _reconnect_forever
    await connection.connect()
  File "C:\Users\ivani\source\repos\optimuspy\.venv\lib\site-packages\carehare\_connection.py", line 89, in connect
    await self._protocol.open
carehare._exceptions.ConnectionClosedByServer: RabbitMQ closed the connection: 403 ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
```

CHANNELS_LAYERS are configured the folowing way:
``` python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_rabbitmq.core.RabbitmqChannelLayer',
        'CONFIG': {
            'host': 'amqp://guest@rabbitmq',
        },
    },
}
```

Note that I am also using RabbitMQ as Celery message broker and it is configured in the same way **and it works**.

**Comment by COOLIRON2311** [comment]
RabbitMQ log:
```
2023-05-29 14:01:54.063000+03:00 [error] <0.2356.0> Error on AMQP connection <0.2356.0> (127.0.0.1:41033 -> 127.0.0.1:5672, state: starting):
2023-05-29 14:01:54.063000+03:00 [error] <0.2356.0> PLAIN login refused: user 'guest' - invalid credentials
2023-05-29 14:01:54.063000+03:00 [info] <0.2356.0> closing AMQP connection <0.2356.0> (127.0.0.1:41033 -> 127.0.0.1:5672)
2023-05-29 14:01:55.074000+03:00 [info] <0.2361.0> accepting AMQP connection <0.2361.0> (127.0.0.1:41037 -> 127.0.0.1:5672)
2023-05-29 14:01:55.076000+03:00 [error] <0.2361.0> Error on AMQP connection <0.2361.0> (127.0.0.1:41037 -> 127.0.0.1:5672, state: starting):
2023-05-29 14:01:55.076000+03:00 [error] <0.2361.0> PLAIN login refused: user 'guest' - invalid credentials
2023-05-29 14:01:55.077000+03:00 [info] <0.2361.0> closing AMQP connection <0.2361.0> (127.0.0.1:41037 -> 127.0.0.1:5672)
2023-05-29 14:01:56.079000+03:00 [info] <0.2366.0> accepting AMQP connection <0.2366.0> (127.0.0.1:41038 -> 127.0.0.1:5672)
2023-05-29 14:01:56.079000+03:00 [error] <0.2366.0> Error on AMQP connection <0.2366.0> (127.0.0.1:41038 -> 127.0.0.1:5672, state: starting):
2023-05-29 14:01:56.079000+03:00 [error] <0.2366.0> PLAIN login refused: user 'guest' - invalid credentials
2023-05-29 14:01:56.079000+03:00 [info] <0.2366.0> closing AMQP connection <0.2366.0> (127.0.0.1:41038 -> 127.0.0.1:5672)

```

**Comment by adamhooper** [comment]
You haven't entered a password. I don't know your password; maybe you should log in as `guest:guest`? Please post your Celery config here: it may contain a clue.

**Comment by COOLIRON2311** [comment]
> You haven't entered a password. I don't know your password; maybe you should log in as `guest:guest`? Please post your Celery config here: it may contain a clue.

You are right. I was missing the password. Now my config is the following:
``` python
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_rabbitmq.core.RabbitmqChannelLayer',
        'CONFIG': {
            'host': 'amqp://guest:guest@rabbitmq',
        },
    },
}
```

But now I am getting another error each time I try to send something through the socket:
```
Exception inside application: Socket has not been accepted, so cannot send over it
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/staticfiles/handlers.py", line 101, in __call__
    return await self.application(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/routing.py", line 62, in __call__
    return await application(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/routing.py", line 116, in __call__
    return await application(
  File "/usr/local/lib/python3.10/dist-packages/channels/consumer.py", line 94, in app
    return await consumer(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/usr/local/lib/python3.10/dist-packages/channels/utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/lib/python3.10/dist-packages/channels/consumer.py", line 73, in dispatch
    await handler(message)
  File "/optimuspy/web/consumers.py", line 24, in ready_announce
    await self.send(text_data=event['task'])
  File "/usr/local/lib/python3.10/dist-packages/channels/generic/websocket.py", line 209, in send
    await super().send({"type": "websocket.send", "text": text_data})
  File "/usr/local/lib/python3.10/dist-packages/channels/consumer.py", line 81, in send
    await self.base_send(message)
  File "/usr/local/lib/python3.10/dist-packages/daphne/server.py", line 240, in handle_reply
    protocol.handle_reply(message)
  File "/usr/local/lib/python3.10/dist-packages/daphne/ws_protocol.py", line 193, in handle_reply
    raise ValueError("Socket has not been accepted, so cannot send over it")
ValueError: Socket has not been accepted, so cannot send over it
WebSocket DISCONNECT /ws/ready/ [172.24.0.1:36988]
```

**Comment by adamhooper** [comment]
This stack trace doesn't include channels_rabbitmq. It's purely from Channels.

Guessing, I think your consumer is trying to send data before it's connected. Probably missing an await, or it's sending in the wrong handler. Mind copy/pasting it?

**Comment by COOLIRON2311** [comment]
> This stack trace doesn't include channels_rabbitmq. It's purely from Channels.
> 
> Guessing, I think your consumer is trying to send data before it's connected. Probably missing an await, or it's sending in the wrong handler. Mind copy/pasting it?

I've figured it out.
I used [the example code](https://github.com/CJWorkbench/channels_rabbitmq#publish-messages-from-celery) from the docs to write Consumer. Turns out `await self.accept()` in `connect` was missing.

 Now it works!
```
WebSocket HANDSHAKING /ws/ready/ [172.24.0.1:37102]
WebSocket CONNECT /ws/ready/ [172.24.0.1:37102]
...
HTTP GET /tasks/2c465a62b26fc0085e2f2649a18a9fe7/result 200 [0.06, 172.24.0.1:37068]
WebSocket DISCONNECT /ws/ready/ [172.24.0.1:37102]
```

Thank you very much for your help!
